
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Jan 28 10:53:17 EST 2000
//----------------------------------------------------

package com.rms.shell.commandline;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REDIRECT_IN = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PIPE = 6;
  public static final int LAST_COMMAND = 5;
  public static final int EARLIER_COMMAND = 4;
  public static final int STRING = 11;
  public static final int REDIRECT_OUT = 9;
  public static final int AMPERSAND = 2;
  public static final int VARIABLE = 12;
  public static final int QUOTED_STRING = 7;
  public static final int SEPARATOR = 10;
  public static final int APPEND = 3;
}

